---
title: "NCAM Explorer"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
---


```{r setup, echo=FALSE}
library(plotly)
library(Matrix)
library(knitr)
library(data.table)
library(webshot)
knitr::opts_knit$set(root.dir = tmp$output_dir)
knitr::opts_chunk$set(echo = FALSE, fig.height = 7, fig.width = 8)
```


```{r data, include=FALSE}

## https://projects.susielu.com/viz-palette?colors=[%22#243a68%22,%22#6a8b3e%22,%22#ff9800%22,%22#f44336%22,%22#9e9e9e%22]&backgroundColor=%22white%22&fontColor=%22black%22&mode=%22normal%22
## https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=243A68&secondary.color=9E9E9E

cols <- c("#243a68", "#6a8b3e", "#ff9800", "#f44336", "#9e9e9e")
cols_rgb <-  paste0("rgb(", apply(col2rgb(cols), 2, paste, collapse = ","), ")")
obs_col <- cols[5]
pred_col <- pos_col <- cols[1]
neg_col <- cols[4]

fit <- tmp$fit # temp object from vis_fit function
if (!is.null(tmp$comp)) { comp <- tmp$comp }
if (!is.null(tmp$last)) { last <- tmp$last }
est <- as.list(fit$sd.rep, "Est")
sd <- as.list(fit$sd.rep, "Std")
est_lwr <- lapply(seq_along(est), function(i) est[[i]] - qnorm(0.975) * sd[[i]])
est_upr <- lapply(seq_along(est), function(i) est[[i]] + qnorm(0.975) * sd[[i]])
names(est_lwr) <- names(est_upr) <- names(est)
tabs <- tidy_model(fit)
if (!is.null(tmp$comp)) { comp_tabs <- tidy_model(model_list = comp) }
if (!is.null(tmp$last)) { last_tabs <- tidy_model(tmp$last) }
if (!is.null(fit$retro)) { retro_tabs <- tidy_retro(fit) } 
min_year <- min(fit$tmb.data$years)
max_year <- max(fit$tmb.data$years)
ages <- fit$tmb.data$ages
years <- fit$tmb.data$years
years_plus1 <- fit$tmb.data$years_plus1


## helper functions for nice Rmarkdown text
text_range <- function(x) paste(range(x), collapse = "-")
text_c <- function(x) {
  paste0(paste(x[-length(x)], collapse = ", "), ", and ", x[length(x)])
}
text_units <- function(x) {
  ifelse(x >= 1000000000, paste0(round(x / 1000000000), "B"),
         ifelse(x >= 1000000, paste0(round(x / 1000000), "M"),
         ifelse(x >= 1000, paste0(round(x / 1000), "k"), 
         as.character(round(x)))))
}

## Function for finding local maxima
## from https://github.com/stas-g/findPeaks
find_peaks <- function (x, m = 3){
  shape <- diff(sign(diff(x, na.pad = FALSE)))
  pks <- sapply(which(shape < 0), FUN = function(i){
    z <- i - m + 1
    z <- ifelse(z > 0, z, 1)
    w <- i + m + 1
    w <- ifelse(w < length(x), w, length(x))
    if(all(x[c(z : i, (i + 2) : w)] <= x[i + 1])) return(i + 1) else return(numeric(0))
  })
  pks <- unlist(pks)
  pks
}

```


```{r background, child = "background.Rmd"}

```


```{r fishery, child = "fishery.Rmd"}

```


```{r surveys, child = "surveys.Rmd"}

```


```{r tagging, child = "tagging.Rmd"}

```


```{r trends, child = "trends.Rmd"}

```


```{r projections, child = "projections.Rmd"}

```


```{r tables, child = "tables.Rmd"}

```







